<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $electronics = Category::where('slug', 'electronics-appliances')->first();
        $smartphones = Category::where('slug', 'smartphones-accessories')->first();
        $fashion     = Category::where('slug', 'fashion-apparel')->first();
        $home        = Category::where('slug', 'home-living')->first();
        $beauty      = Category::where('slug', 'beauty-personal-care')->first();
        $grocery     = Category::where('slug', 'daily-essentials-grocery')->first();

        $samsung  = Brand::where('slug', 'samsung')->first();
        $apple    = Brand::where('slug', 'apple')->first();
        $sony     = Brand::where('slug', 'sony')->first();
        $nike     = Brand::where('slug', 'nike')->first();
        $shopcalm = Brand::where('slug', 'shopcalm-essentials')->first();

        $products = [
            [
                'name'              => 'Samsung Galaxy S24 Ultra 5G',
                'slug'              => 'samsung-galaxy-s24-ultra-5g',
                'sku'               => 'SAM-S24U-256',
                'category_id'       => $smartphones?->id,
                'brand_id'          => $samsung?->id,
                'product_type'      => 'simple',
                'short_description' => '200MP Camera, Snapdragon 8 Gen 3, Titanium Gray, 12GB RAM / 256GB Storage.',
                'description'       => 'Experience the ultimate AI smartphone with Galaxy AI features, Circle to Search, Live Translate, and Note Assist. Features a stunning 6.8-inch Dynamic AMOLED 2X 120Hz display with S-Pen support.',
                'cost_price'        => 95000.00,
                'price'             => 129999.00,
                'stock'             => 25,
                'featured'          => true,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.23,
                'length'            => 16.20,
                'width'             => 7.90,
                'height'            => 0.86,
                'hsn_code'          => '8517',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'Apple iPhone 15 Pro Max',
                'slug'              => 'apple-iphone-15-pro-max',
                'sku'               => 'APL-IP15PM-256',
                'category_id'       => $smartphones?->id,
                'brand_id'          => $apple?->id,
                'product_type'      => 'simple',
                'short_description' => 'Titanium design, A17 Pro chip, Action button, 48MP Main camera with 5x Telephoto.',
                'description'       => 'Forged in titanium and featuring the groundbreaking A17 Pro chip, customizable Action button, and the most powerful iPhone camera system ever with 5x optical zoom.',
                'cost_price'        => 120000.00,
                'price'             => 149900.00,
                'stock'             => 20,
                'featured'          => true,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.22,
                'length'            => 15.99,
                'width'             => 7.67,
                'height'            => 0.83,
                'hsn_code'          => '8517',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
                'slug'              => 'sony-wh-1000xm5-headphones',
                'sku'               => 'SNY-WH1000XM5-BLK',
                'category_id'       => $electronics?->id,
                'brand_id'          => $sony?->id,
                'product_type'      => 'simple',
                'short_description' => 'Industry leading noise cancellation with Auto NC Optimizer and 30-hr battery life.',
                'description'       => 'Two processors control 8 microphones for unprecedented noise canceling and exceptional call quality. Speak-to-Chat tech automatically pauses playback when you start a conversation.',
                'cost_price'        => 22000.00,
                'price'             => 29990.00,
                'stock'             => 40,
                'featured'          => true,
                'trending'          => false,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.25,
                'length'            => 22.00,
                'width'             => 18.00,
                'height'            => 7.50,
                'hsn_code'          => '8518',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'Sony Bravia 55" 4K Ultra HD Smart OLED TV',
                'slug'              => 'sony-bravia-55-4k-oled-tv',
                'sku'               => 'SNY-TV-55OLED',
                'category_id'       => $electronics?->id,
                'brand_id'          => $sony?->id,
                'product_type'      => 'simple',
                'short_description' => 'Cognitive Processor XR, Acoustic Surface Audio+, Dolby Vision, Google TV.',
                'description'       => 'Pure black contrast with Cognitive Processor XR. Acoustic Surface Audio+ turns the screen into a multi-channel speaker for immersive sound aligned with images.',
                'cost_price'        => 85000.00,
                'price'             => 114990.00,
                'stock'             => 15,
                'featured'          => false,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
                'weight'            => 17.50,
                'length'            => 122.70,
                'width'             => 71.20,
                'height'            => 5.30,
                'hsn_code'          => '8528',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'Nike Air Zoom Pegasus 40 Running Shoes',
                'slug'              => 'nike-air-zoom-pegasus-40',
                'sku'               => 'NKE-PEG40-BLK',
                'category_id'       => $fashion?->id,
                'brand_id'          => $nike?->id,
                'product_type'      => 'simple',
                'short_description' => 'Lightweight neutral running sneaker with dual Zoom Air units for extra pop.',
                'description'       => 'A springy ride for every run. Pegasus familiar, just-for-you feel returns to help you accomplish your goals with improved midfoot lockdown and comfortable upper mesh.',
                'cost_price'        => 7000.00,
                'price'             => 11895.00,
                'stock'             => 60,
                'featured'          => true,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.85,
                'length'            => 32.00,
                'width'             => 20.00,
                'height'            => 12.00,
                'hsn_code'          => '6404',
                'tax_rate'          => 12.00,
            ],
            [
                'name'              => 'Nike Tech Fleece Hoodie & Joggers Set',
                'slug'              => 'nike-tech-fleece-hoodie-set',
                'sku'               => 'NKE-TCFLC-SET',
                'category_id'       => $fashion?->id,
                'brand_id'          => $nike?->id,
                'product_type'      => 'simple',
                'short_description' => 'Premium lightweight fleece offering warmth without added bulk.',
                'description'       => 'Crafted with double-sided smooth fleece, this streetwear track ensemble features iconic chevron lines and zip utility pockets for everyday urban comfort.',
                'cost_price'        => 6500.00,
                'price'             => 9995.00,
                'stock'             => 35,
                'featured'          => false,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.90,
                'length'            => 35.00,
                'width'             => 25.00,
                'height'            => 5.00,
                'hsn_code'          => '6101',
                'tax_rate'          => 12.00,
            ],
            [
                'name'              => 'ShopCalm Minimalist Ergonomic Desk Lamp',
                'slug'              => 'shopcalm-minimalist-desk-lamp',
                'sku'               => 'SCM-LAMP-MINI',
                'category_id'       => $home?->id,
                'brand_id'          => $shopcalm?->id,
                'product_type'      => 'simple',
                'short_description' => 'Touch dimmable LED study light with ambient warm light modes and phone dock.',
                'description'       => 'Bring tranquil illuminating aesthetics to your study setup. Features 5 color temperatures, flicker-free eye preservation LED technology, and integrated wireless fast-charging base.',
                'cost_price'        => 1200.00,
                'price'             => 2499.00,
                'stock'             => 100,
                'featured'          => true,
                'trending'          => false,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
                'weight'            => 1.10,
                'length'            => 18.00,
                'width'             => 14.00,
                'height'            => 42.00,
                'hsn_code'          => '9405',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'ShopCalm Organic Bamboo Bed Sheet Set (King)',
                'slug'              => 'shopcalm-bamboo-sheet-set',
                'sku'               => 'SCM-BED-BAMBOO',
                'category_id'       => $home?->id,
                'brand_id'          => $shopcalm?->id,
                'product_type'      => 'simple',
                'short_description' => '100% pure organic viscose bamboo sheets, silky smooth and cooling.',
                'description'       => 'Experience five-star hotel comfort every night. Naturally hypoallergenic, temperature regulating, and ultra breathable bamboo weaves designed for soothing sleep.',
                'cost_price'        => 2200.00,
                'price'             => 3999.00,
                'stock'             => 50,
                'featured'          => false,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&auto=format&fit=crop&q=80',
                'weight'            => 2.10,
                'length'            => 30.00,
                'width'             => 25.00,
                'height'            => 8.00,
                'hsn_code'          => '6302',
                'tax_rate'          => 12.00,
            ],
            [
                'name'              => 'Botanical Hydrating Face Serum 50ml',
                'slug'              => 'botanical-hydrating-face-serum',
                'sku'               => 'SCM-BEAUTY-SERUM',
                'category_id'       => $beauty?->id,
                'brand_id'          => $shopcalm?->id,
                'product_type'      => 'simple',
                'short_description' => 'Hyaluronic acid & Niacinamide serum for radiant glow and glass skin effect.',
                'description'       => 'Formulated with cold-pressed botanical extracts and triple molecular weight hyaluronic acid to deeply hydrate skin barrier and minimize pore visibility.',
                'cost_price'        => 450.00,
                'price'             => 999.00,
                'stock'             => 80,
                'featured'          => true,
                'trending'          => false,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.15,
                'length'            => 5.00,
                'width'             => 5.00,
                'height'            => 12.00,
                'hsn_code'          => '3304',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'Luxury Scented Soy Candle Set',
                'slug'              => 'luxury-scented-soy-candle-set',
                'sku'               => 'SCM-CANDLE-SET',
                'category_id'       => $home?->id,
                'brand_id'          => $shopcalm?->id,
                'product_type'      => 'simple',
                'short_description' => 'Set of 3 handcrafted soy wax candles in Amber, French Vanilla, and Lavender.',
                'description'       => 'Hand-poured with natural soy wax and essential oils. Provides over 45 hours of clean burning warmth to transform your living room into a relaxing spa sanctuary.',
                'cost_price'        => 600.00,
                'price'             => 1299.00,
                'stock'             => 70,
                'featured'          => false,
                'trending'          => false,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.75,
                'length'            => 24.00,
                'width'             => 8.00,
                'height'            => 10.00,
                'hsn_code'          => '3406',
                'tax_rate'          => 18.00,
            ],
            [
                'name'              => 'Gourmet Roasted Organic Dry Fruit Mix 500g',
                'slug'              => 'gourmet-roasted-dry-fruit-mix',
                'sku'               => 'SCM-GROC-NUTS',
                'category_id'       => $grocery?->id,
                'brand_id'          => $shopcalm?->id,
                'product_type'      => 'simple',
                'short_description' => 'Premium California Almonds, Cashews, Pistachios, and Turkish Raisins.',
                'description'       => 'Lightly salted and dry roasted without oil. Rich in Omega-3, antioxidants, and proteins for a healthy daily snack. Packed in a resealable zip pouch.',
                'cost_price'        => 350.00,
                'price'             => 649.00,
                'stock'             => 120,
                'featured'          => true,
                'trending'          => true,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80',
                'weight'            => 0.55,
                'length'            => 20.00,
                'width'             => 15.00,
                'height'            => 6.00,
                'hsn_code'          => '0802',
                'tax_rate'          => 5.00,
            ],
            [
                'name'              => 'Cold-Pressed Virgin Coconut Oil 1L',
                'slug'              => 'cold-pressed-virgin-coconut-oil',
                'sku'               => 'SCM-GROC-COCOIL',
                'category_id'       => $grocery?->id,
                'brand_id'          => $shopcalm?->id,
                'product_type'      => 'simple',
                'short_description' => '100% pure raw unrefined coconut oil for cooking, hair, and skincare.',
                'description'       => 'Extracted using traditional wood-pressing technique to preserve rich aroma, natural nutrients, and lauric acid without heat processing or chemical additives.',
                'cost_price'        => 220.00,
                'price'             => 449.00,
                'stock'             => 90,
                'featured'          => false,
                'trending'          => false,
                'status'            => 'Active',
                'main_image'        => 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
                'weight'            => 1.05,
                'length'            => 10.00,
                'width'             => 10.00,
                'height'            => 22.00,
                'hsn_code'          => '1513',
                'tax_rate'          => 5.00,
            ],
        ];

        foreach ($products as $prod) {
            Product::updateOrCreate(['sku' => $prod['sku']], $prod);
        }
    }
}
